number_one = int(input("Enter first number: "))
number_two = int(input("Enter second number: "))
print(number_one, "+", number_two, "=", number_one+number_two)
print(number_one, "-", number_two, "=", number_one-number_two)
print(number_one, "/", number_two, "=", number_one/number_two)
print(number_one, "*", number_two, "=", number_one*number_two)       
print(number_one, "**", number_two, "=", number_one**number_two)