a = int(input("please enter value for 'a': "))
b = int(input("please enter value for 'b': "))
print ('a plus b:',a+b)
print ('a minus b:',a-b)
print ('a multiply b:',a*b)
print ('a devide b:',a/b)
print ('division of operands:',a//b)
print ('Divides the left operand by the right:',a%b)
print ('exponential calculation of operators:',a**b)