user_name = input("What is your name?\n")
print("Hello,", user_name)
user_age = input("How old are you?\n")
print("Your age is ", user_age)
user_loc = input("Where do you live?\n")
print("Your live in ", user_loc)