a = int(input("please enter value for 'a': "))
b = int(input("please enter value for 'b': "))
print ('a+b:',a+b)
print ('a+b:',a-b)
print ('a+b:',a*b)
print ('a+b:',a/b)
print ('a+b:',a//b)
print ('a+b:',a%b)
print ('a+b:',a**b)