file = open("zen.txt")
text = file.read()
file.close()
num_of_better = text.count("better")
num_of_is = text.count("is")
num_of_never = text.count("never")
print(f"The word 'better' was repeated {num_of_better} times")
print(f"The word 'is' was repeated {num_of_is} times")
print(f"The word 'never' was repeated {num_of_never} times", "\n")
print(text.upper(), "\n")
print(text.replace('i' , '&'))