file = open('Zen.txt')
philosophy = file.read()
file.close()
num_of_better = philosophy.count("better")
num_of_is = philosophy.count("is")
num_of_never = philosophy.count("never")
print(f"The word 'better' is repeated {num_of_better} times")
print(f"The word 'is' is repeated {num_of_is} times")
print(f"The word 'never' is repeated {num_of_never} times\n")
print(philosophy.upper(), '\n')
print(philosophy.replace("i", "&"))