num = input("Введіть число = ")
num = str(num)
print('Реверсне = ', num[::-1])
a = int(num[0])
b = int(num[1])
c = int(num[2])
d = int(num[3])
print("Добуток = ", a * b * c * d)
list = [n for n in num]
sorted_list = sorted(list)
print("Посортоване число = ", sorted_list)